language: cpp

matrix:
  include: 
  - compiler: gcc
    env: TRAVIS_BUILD_TYPE=Release
  - compiler: clang
    env: TRAVIS_BUILD_TYPE=Debug
  - compiler: gcc
    env: TRAVIS_BUILD_TYPE=Debug
  - compiler: clang
    env: TRAVIS_BUILD_TYPE=Release
  

before_script:
  - sudo apt-get install gfortran libboost-system-dev libboost-serialization-dev libboost-signals-dev libboost-test-dev libboost-filesystem-dev  libboost-date-time-dev
  - mkdir build
  - cd build
  - gcc --version
  - clang --version
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DGURLS_USE_EXTERNAL_BLAS_LAPACK:BOOL=ON ./..


script: 
  - make
  - sudo make install
