language: cpp

compiler: 
  - gcc
  - clang
  
env:   
  - TRAVIS_BUILD_TYPE=Release
  - TRAVIS_BUILD_TYPE=Debug

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo apt-get install gfortran libboost-system-dev libboost-serialization-dev libboost-signals-dev libboost-test-dev libboost-filesystem-dev  libboost-date-time-dev
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DGURLS_USE_EXTERNAL_BLAS_LAPACK:BOOL=ON ./..


script: 
  - make
  - sudo make install
